matrix:
  include:
  - if: tag =~ .+
    os: osx
    osx_image: xcode7.3
  - os: linux
    language: python
    python: 2.7
    sudo: required
    services:
    - docker
    addons:
      apt:
        packages:
        - libusb-1.0-0-dev
        - libudev-dev
before_install:
- source contrib/travis/electrum_axe_version_env.sh
- echo electrum-axe version is $ELECTRUM_AXE_VERSION
- mkdir -p build && cp contrib/travis/* ./build/ && if [[ $TRAVIS_OS_NAME == 'osx'
  ]]; then ./build/before_install-osx.sh ; else ./build/before_install-linux.sh ;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then pip install tox;
  fi
script:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then tox; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./build/travis-build-osx.sh ; else ./build/travis-build-linux.sh;
  fi
after_success:
- if [ "$TRAVIS_BRANCH" = "master" ] && [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME
  == 'linux' ]]; then pip install pycurl requests && contrib/make_locale; fi
deploy:
- provider: releases
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDGpiiOMrUG/w2kEap2bQKoU3B9wXclnPnYp4JjJHBEuGwJUm00Pai+kE13jnKRzHvH4785FpWYvCbTQuappo2iOzIf5VylljvHpTArG48CGugPDgQlvsqxE+iX0I2LzJeByp02rKeLXBEqr2ConmUcApP82aMTvSW+qrGXgmMxpm4/xXxqreWFixvxxfuO0sS5eRgrw4TO9PArz8KyKp8lSW3VAFDG6v8oYceOAOOE+XNGc6FCfObqC3XlMe49hnvp4F/5RrVEILjex2Mad86//NCCy98apO+J0PdnBD9XUpIFUZEv2fLRtMg8enMoGlNR9+r6Y1WJDoBQ3Lj5MNM9dWq50KuJYxkx7nZu0XqBupP7+gE17nlSY5z2eEw2zD4pJay4dj/iv1+tYhJu/pUweh8EY31zfFGckGxy4FkTzMhU7czXgmJ57UlP2s6sBEjFnHlAgPMCCISU7fcPkqfiMbvSO1FXcCuHwjzCKdmnnkOB5YR9gWQm8H1GVEKcPhpe3jlVtWQzRWafJFt7CFnhKmfZJHXKa8v+n8nRbayDYPU8TqxJs2Z02GGqQ/SXFQqSYWvwi4WTaG0hKC262QUvoS94/BLqjuSIzUteDPzf3+N9qH2XLqOtAr4gttCz3XPAIjywsrliHw9wZ4ILgCkpyoj4YeENxeDwilE1evt/RQ=
  file:
  - build/electrum-axe/dist/electrum-axe-$ELECTRUM_AXE_VERSION-macosx.dmg
  on:
    repo: axerunners/electrum-axe
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  #api_key:
    #secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDGpiiOMrUG/w2kEap2bQKoU3B9wXclnPnYp4JjJHBEuGwJUm00Pai+kE13jnKRzHvH4785FpWYvCbTQuappo2iOzIf5VylljvHpTArG48CGugPDgQlvsqxE+iX0I2LzJeByp02rKeLXBEqr2ConmUcApP82aMTvSW+qrGXgmMxpm4/xXxqreWFixvxxfuO0sS5eRgrw4TO9PArz8KyKp8lSW3VAFDG6v8oYceOAOOE+XNGc6FCfObqC3XlMe49hnvp4F/5RrVEILjex2Mad86//NCCy98apO+J0PdnBD9XUpIFUZEv2fLRtMg8enMoGlNR9+r6Y1WJDoBQ3Lj5MNM9dWq50KuJYxkx7nZu0XqBupP7+gE17nlSY5z2eEw2zD4pJay4dj/iv1+tYhJu/pUweh8EY31zfFGckGxy4FkTzMhU7czXgmJ57UlP2s6sBEjFnHlAgPMCCISU7fcPkqfiMbvSO1FXcCuHwjzCKdmnnkOB5YR9gWQm8H1GVEKcPhpe3jlVtWQzRWafJFt7CFnhKmfZJHXKa8v+n8nRbayDYPU8TqxJs2Z02GGqQ/SXFQqSYWvwi4WTaG0hKC262QUvoS94/BLqjuSIzUteDPzf3+N9qH2XLqOtAr4gttCz3XPAIjywsrliHw9wZ4ILgCkpyoj4YeENxeDwilE1evt/RQ=
  file:
  - build/electrum-axe/dist/Electrum-AXE-$ELECTRUM_AXE_VERSION.tar.gz
  - build/electrum-axe/dist/electrum-axe-$ELECTRUM_AXE_VERSION-setup.exe
  on:
    repo: axerunners/electrum-axe
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
